import { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext(null);

export const LANGUAGES = { IT: 'it', FR: 'fr', EN: 'en' };
export const LANGUAGE_LABELS = {
  [LANGUAGES.IT]: 'Italiano',
  [LANGUAGES.FR]: 'Français',
  [LANGUAGES.EN]: 'English'
};

const translations = {
  [LANGUAGES.FR]: {
    appTitle: 'CAMI ALUMINIUM',
    appSubtitle: 'Système de Gestion d\'Inventaire',
    navInventory: 'Inventaire',
    navProjects: 'Projets',
    image: 'Image', designation: 'Désignation', quantity: 'Quantité',
    orderedQuantity: 'Qté Commandée', threshold: 'Seuil', status: 'Statut',
    actions: 'Actions', inStock: 'En Stock', lowStock: 'Stock Faible',
    criticalStock: 'Stock Critique', warningStock: 'Alerte Stock',
    edit: 'Modifier', delete: 'Supprimer', add: 'Ajouter',
    cancel: 'Annuler', save: 'Enregistrer', confirm: 'Confirmer',
    addNewItem: 'Ajouter Barre', editItem: 'Modifier Barre',
    imageUrl: 'URL Image', designationIt: 'Désignation (IT)',
    designationFr: 'Désignation (FR)', designationEn: 'Désignation (EN)',
    quantityLabel: 'Quantité', orderedQuantityLabel: 'Qté Commandée',
    thresholdLabel: 'Seuil Minimum', categoryLabel: 'Catégorie',
    noCategory: 'Aucune Catégorie', showAll: 'Tout Afficher',
    showLowStock: 'Stock Faible Uniquement',
    searchPlaceholder: 'Rechercher par désignation...',
    addCategory: 'Ajouter Catégorie', deleteConfirmTitle: 'Confirmer Suppression',
    deleteConfirmMessage: 'Êtes-vous sûr de vouloir supprimer cet article?',
    deleteCategoryConfirmMessage: 'Êtes-vous sûr de vouloir supprimer cette catégorie?',
    noItems: 'Aucun article trouvé',
    noItemsDescription: 'Commencez par ajouter votre premier article',
    requiredField: 'Champ obligatoire', invalidNumber: 'Entrez un nombre valide',
    itemAdded: 'Article ajouté', itemUpdated: 'Article mis à jour',
    itemDeleted: 'Article supprimé', create: 'Créer', update: 'Mettre à jour',
    close: 'Fermer', exporting: 'Exportation...', exportExcel: 'Exporter Excel',
    exportSuccess: 'Excel exporté', exportError: 'Erreur exportation',
    projectsTitle: 'Projets', addProject: 'Nouveau Projet',
    noProjects: 'Aucun projet trouvé', loading: 'Chargement...',
    projectSearchPlaceholder: 'Rechercher un projet...',
    status_en_cours: 'En cours', status_termine: 'Terminé', status_livre: 'Livré',
    chassisWord: 'châssis', barsWord: 'barres',
    deleteProjectConfirm: 'Supprimer ce projet ? Le stock des barres sera restauré.',
    projectTitleAdd: 'Nouveau Projet', projectTitleEdit: 'Modifier le Projet',
    projectName: 'Nom du projet', reference: 'Référence',
    ralCode: 'Code RAL', ralColor: 'Couleur RAL', date: 'Date',
    projectStatus: 'Statut', ref: 'Réf.', ral: 'RAL',
    backToProjects: '← Projets', tabChassis: 'Châssis', tabBars: 'Barres utilisées',
    addChassis: 'Ajouter châssis', exportPDF: 'Exporter PDF',
    printSelected: 'Imprimer sélection', printLabel: 'Étiquette',
    selectAll: 'Tout sélectionner', deselectAll: 'Tout désélectionner',
    selectedCount: 'sélectionné(s)',
    chassis: 'Châssis', repere: 'Repère', type: 'Type',
    largeur: 'Largeur', hauteur: 'Hauteur', quantityChassis: 'Qté',
    dimension: 'Dimension', etat: 'État',
    noChassis: 'Aucun châssis ajouté', deleteChassisConfirm: 'Supprimer ce châssis ?',
    etat_non_entame: 'Non entamé', etat_en_cours: 'En cours',
    etat_fabrique: 'Fabriqué', etat_livre: 'Livré',
    chassisTitleAdd: 'Ajouter un châssis', chassisTitleEdit: 'Modifier le châssis',
    chassisType: 'Type de châssis', chassisEtat: 'État',
    dormant: 'Dormant', vantail: 'Vantail',
    componentsDimensions: 'Dimensions des composants',
    print: 'Imprimer', labelPreview: 'Aperçu étiquette',
    labelProject: 'Projet', labelRef: 'Réf.', labelRal: 'RAL',
    labelRepere: 'Repère', labelType: 'Type', labelDim: 'Dim.',
    labelEtat: 'État', labelQty: 'Qté',
    usedBarsTitle: 'Barres utilisées', noUsedBars: 'Aucune barre utilisée',
    barDesignation: 'Désignation', barQtyUsed: 'Qté utilisée',
    barStockRemaining: 'Stock restant',
  },
  [LANGUAGES.IT]: {
    appTitle: 'CAMI ALUMINIUM',
    appSubtitle: 'Sistema di Gestione Inventario',
    navInventory: 'Inventario', navProjects: 'Progetti',
    image: 'Immagine', designation: 'Designazione', quantity: 'Quantità',
    orderedQuantity: 'Qta Ordinata', threshold: 'Soglia', status: 'Stato',
    actions: 'Azioni', inStock: 'Disponibile', lowStock: 'Scorte Basse',
    criticalStock: 'Stock Critico', warningStock: 'Avviso Stock',
    edit: 'Modifica', delete: 'Elimina', add: 'Aggiungi',
    cancel: 'Annulla', save: 'Salva', confirm: 'Conferma',
    addNewItem: 'Aggiungi Barra', editItem: 'Modifica Barra',
    imageUrl: 'URL Immagine', designationIt: 'Designazione (IT)',
    designationFr: 'Designazione (FR)', designationEn: 'Designazione (EN)',
    quantityLabel: 'Quantità', orderedQuantityLabel: 'Qta Ordinata',
    thresholdLabel: 'Soglia Minima', categoryLabel: 'Categoria',
    noCategory: 'Nessuna Categoria', showAll: 'Mostra Tutto',
    showLowStock: 'Solo Scorte Basse',
    searchPlaceholder: 'Cerca per designazione...',
    addCategory: 'Aggiungi Categoria', deleteConfirmTitle: 'Conferma Eliminazione',
    deleteConfirmMessage: 'Sei sicuro di voler eliminare questo articolo?',
    deleteCategoryConfirmMessage: 'Sei sicuro di voler eliminare questa categoria?',
    noItems: 'Nessun articolo trovato',
    noItemsDescription: 'Inizia aggiungendo il tuo primo articolo',
    requiredField: 'Campo obbligatorio', invalidNumber: 'Inserisci un numero valido',
    itemAdded: 'Articolo aggiunto', itemUpdated: 'Articolo aggiornato',
    itemDeleted: 'Articolo eliminato', create: 'Crea', update: 'Aggiorna',
    close: 'Chiudi', exporting: 'Esportazione...', exportExcel: 'Esporta Excel',
    exportSuccess: 'Excel esportato', exportError: 'Errore esportazione',
    projectsTitle: 'Progetti', addProject: 'Nuovo Progetto',
    noProjects: 'Nessun progetto trovato', loading: 'Caricamento...',
    projectSearchPlaceholder: 'Cerca progetto...',
    status_en_cours: 'In corso', status_termine: 'Terminato', status_livre: 'Consegnato',
    chassisWord: 'telai', barsWord: 'barre',
    deleteProjectConfirm: 'Eliminare questo progetto? Lo stock delle barre verrà ripristinato.',
    projectTitleAdd: 'Nuovo Progetto', projectTitleEdit: 'Modifica Progetto',
    projectName: 'Nome progetto', reference: 'Riferimento',
    ralCode: 'Codice RAL', ralColor: 'Colore RAL', date: 'Data',
    projectStatus: 'Stato', ref: 'Rif.', ral: 'RAL',
    backToProjects: '← Progetti', tabChassis: 'Telai', tabBars: 'Barre utilizzate',
    addChassis: 'Aggiungi telaio', exportPDF: 'Esporta PDF',
    printSelected: 'Stampa selezione', printLabel: 'Etichetta',
    selectAll: 'Seleziona tutto', deselectAll: 'Deseleziona tutto',
    selectedCount: 'selezionato/i',
    chassis: 'Telaio', repere: 'Repere', type: 'Tipo',
    largeur: 'Larghezza', hauteur: 'Altezza', quantityChassis: 'Qtà',
    dimension: 'Dimensione', etat: 'Stato',
    noChassis: 'Nessun telaio aggiunto', deleteChassisConfirm: 'Eliminare questo telaio?',
    etat_non_entame: 'Non iniziato', etat_en_cours: 'In corso',
    etat_fabrique: 'Fabbricato', etat_livre: 'Consegnato',
    chassisTitleAdd: 'Aggiungi telaio', chassisTitleEdit: 'Modifica telaio',
    chassisType: 'Tipo telaio', chassisEtat: 'Stato',
    dormant: 'Dormiente', vantail: 'Anta',
    componentsDimensions: 'Dimensioni componenti',
    print: 'Stampa', labelPreview: 'Anteprima etichetta',
    labelProject: 'Progetto', labelRef: 'Rif.', labelRal: 'RAL',
    labelRepere: 'Repere', labelType: 'Tipo', labelDim: 'Dim.',
    labelEtat: 'Stato', labelQty: 'Qtà',
    usedBarsTitle: 'Barre utilizzate', noUsedBars: 'Nessuna barra utilizzata',
    barDesignation: 'Designazione', barQtyUsed: 'Qtà usata',
    barStockRemaining: 'Stock rimanente',
  },
  [LANGUAGES.EN]: {
    appTitle: 'CAMI ALUMINIUM',
    appSubtitle: 'Inventory Management System',
    navInventory: 'Inventory', navProjects: 'Projects',
    image: 'Image', designation: 'Designation', quantity: 'Quantity',
    orderedQuantity: 'Ordered Qty', threshold: 'Threshold', status: 'Status',
    actions: 'Actions', inStock: 'In Stock', lowStock: 'Low Stock',
    criticalStock: 'Critical Stock', warningStock: 'Warning Stock',
    edit: 'Edit', delete: 'Delete', add: 'Add',
    cancel: 'Cancel', save: 'Save', confirm: 'Confirm',
    addNewItem: 'Add Bar', editItem: 'Edit Bar',
    imageUrl: 'Image URL', designationIt: 'Designation (IT)',
    designationFr: 'Designation (FR)', designationEn: 'Designation (EN)',
    quantityLabel: 'Quantity', orderedQuantityLabel: 'Ordered Qty',
    thresholdLabel: 'Minimum Threshold', categoryLabel: 'Category',
    noCategory: 'No Category', showAll: 'Show All',
    showLowStock: 'Low Stock Only',
    searchPlaceholder: 'Search by designation...',
    addCategory: 'Add Category', deleteConfirmTitle: 'Confirm Deletion',
    deleteConfirmMessage: 'Are you sure you want to delete this item?',
    deleteCategoryConfirmMessage: 'Are you sure you want to delete this category?',
    noItems: 'No items found',
    noItemsDescription: 'Start by adding your first item to the inventory',
    requiredField: 'Required field', invalidNumber: 'Enter a valid number',
    itemAdded: 'Item added', itemUpdated: 'Item updated',
    itemDeleted: 'Item deleted', create: 'Create', update: 'Update',
    close: 'Close', exporting: 'Exporting...', exportExcel: 'Export Excel',
    exportSuccess: 'Excel exported', exportError: 'Export error',
    projectsTitle: 'Projects', addProject: 'New Project',
    noProjects: 'No projects found', loading: 'Loading...',
    projectSearchPlaceholder: 'Search projects...',
    status_en_cours: 'In Progress', status_termine: 'Completed', status_livre: 'Delivered',
    chassisWord: 'chassis', barsWord: 'bars',
    deleteProjectConfirm: 'Delete this project? Bar stock will be restored.',
    projectTitleAdd: 'New Project', projectTitleEdit: 'Edit Project',
    projectName: 'Project name', reference: 'Reference',
    ralCode: 'RAL Code', ralColor: 'RAL Color', date: 'Date',
    projectStatus: 'Status', ref: 'Ref.', ral: 'RAL',
    backToProjects: '← Projects', tabChassis: 'Chassis', tabBars: 'Used Bars',
    addChassis: 'Add Chassis', exportPDF: 'Export PDF',
    printSelected: 'Print selection', printLabel: 'Label',
    selectAll: 'Select all', deselectAll: 'Deselect all',
    selectedCount: 'selected',
    chassis: 'Chassis', repere: 'ID', type: 'Type',
    largeur: 'Width', hauteur: 'Height', quantityChassis: 'Qty',
    dimension: 'Dimension', etat: 'Status',
    noChassis: 'No chassis added yet', deleteChassisConfirm: 'Delete this chassis?',
    etat_non_entame: 'Not Started', etat_en_cours: 'In Progress',
    etat_fabrique: 'Fabricated', etat_livre: 'Delivered',
    chassisTitleAdd: 'Add Chassis', chassisTitleEdit: 'Edit Chassis',
    chassisType: 'Chassis Type', chassisEtat: 'Status',
    dormant: 'Frame', vantail: 'Leaf',
    componentsDimensions: 'Component Dimensions',
    print: 'Print', labelPreview: 'Label Preview',
    labelProject: 'Project', labelRef: 'Ref.', labelRal: 'RAL',
    labelRepere: 'ID', labelType: 'Type', labelDim: 'Dim.',
    labelEtat: 'Status', labelQty: 'Qty',
    usedBarsTitle: 'Used Bars', noUsedBars: 'No bars used',
    barDesignation: 'Designation', barQtyUsed: 'Qty used',
    barStockRemaining: 'Remaining stock',
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(LANGUAGES.FR);

  const changeLanguage = useCallback((lang) => {
    if (Object.values(LANGUAGES).includes(lang)) setCurrentLanguage(lang);
  }, []);

  const t = useCallback((key) => translations[currentLanguage]?.[key] || key, [currentLanguage]);

  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t, languages: LANGUAGES, languageLabels: LANGUAGE_LABELS }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export default LanguageContext;
