import { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext(null);
export const LANGUAGES = { IT: 'it', FR: 'fr', EN: 'en' };
export const LANGUAGE_LABELS = { [LANGUAGES.IT]: 'Italiano', [LANGUAGES.FR]: 'Français', [LANGUAGES.EN]: 'English' };

const translations = {
  fr: {
    appTitle: 'CAMI ALUMINIUM', appSubtitle: 'PAR HB',
    navInventory: 'Inventaire', navOrders: 'Commandes', navProjects: 'Projets',
    navClients: 'Clients', navDevis: 'Devis', navMovements: 'Mouvements',
    navAnalytics: 'Dashboard', navAdmin: 'Admin',
    navAtelierTables: 'AtelierTables',
    connectez: "Connectez-vous", utilisateur: "Nom d'utilisateur", mdp: "Mot de passe",
    login_loading: "Connexion...", login_button: "Se connecter",
    backCommandes: "Retour aux commandes",
    barStockRemaining: 'Stock restant',
    Demandesadmin: 'Demandes admin',
    mdpoubliécontactezadmin: "Mot de passe oublié ? Contactez l'administrateur",
    allCompanies: 'Tout', company: 'Société', language: 'Langue',
    changePassword: 'Changer le mot de passe', logout: 'Se déconnecter',
    image: 'Image', designation: 'Désignation', quantity: 'Quantité',
    orderedQuantity: 'Qté Commandée', threshold: 'Seuil', status: 'Statut',
    actions: 'Actions', inStock: 'En Stock', lowStock: 'Stock Faible',
    criticalStock: 'Stock Critique', warningStock: 'Alerte Stock',
    edit: 'Modifier', delete: 'Supprimer', add: 'Ajouter',
    cancel: 'Annuler', save: 'Enregistrer', confirm: 'Confirmer',
    close: 'Fermer', create: 'Créer', update: 'Mettre à jour',
    loading: 'Chargement...', noData: 'Aucune donnée', refresh: 'Actualiser',
    addNewItem: 'Ajouter article', editItem: "Modifier l'article",
    imageUrl: 'URL Image', quantityLabel: 'Quantité', orderedQuantityLabel: 'Qté Commandée',
    thresholdLabel: 'Seuil Minimum', categoryLabel: 'Catégorie',
    noCategory: 'Aucune Catégorie', showAll: 'Tout Afficher',
    searchPlaceholder: 'Rechercher par désignation...',
    addCategory: 'Ajouter Catégorie', editCategory: 'Modifier Catégorie',
    deleteConfirmMessage: 'Êtes-vous sûr de vouloir supprimer cet article?',
    deleteCategoryConfirmMessage: 'Êtes-vous sûr de vouloir supprimer cette catégorie?',
    noItems: 'Aucun article trouvé',
    exporting: 'Exportation...', exportExcel: 'Exporter Excel',
    exportSuccess: 'Excel exporté', exportError: 'Erreur exportation',
    takeOutTitle: 'Retirer du stock', takeOutAvailable: 'disponible',
    takeOutQtyLabel: 'Quantité à retirer', takeOutNoteLabel: 'Raison / Note',
    takeOutPlaceholder: 'ex: Utilisé pour...', takeOutConfirm: 'Confirmer', takeOutCancel: 'Annuler',
    addInTitle: 'Ajouter au stock', addInQtyLabel: 'Quantité à ajouter',
    addInPlaceholder: "Raison d'ajout...", addInConfirm: 'Confirmer',
    errorUpdating: 'Erreur de mise à jour',
    addSuperCategory: 'Ajouter super-catégorie', superCategoryKey: 'Identifiant (unique)',
    superCategoryColor: 'Couleur',
    deleteSuperCatConfirm: 'Supprimer cette super-catégorie? Tous les articles et catégories associés seront affectés.',
    manageSuperCats: 'Gérer les super-catégories',
    poudre: 'Poudre', accessDenied: 'Accès refusé',
    // Orders
    orderDetailLinesTitle: 'Articles commandés',
    orderAlreadyReceived: 'Déjà reçu :',
    orderReceiveQtyLabel: 'Quantité totale reçue (cumulative)',
    orderConfirmReceive: '✓ Confirmer réception',
    orderReceiveTitle: 'Réceptionner des articles',
    orderReceiveBtn: 'Réceptionner',
    orderNotes: 'Notes :',
    orderNew: 'Nouvelle commande',
    etat_non_vitre: "Non vitré",
    orderEdit: 'Modifier la commande',
    orderNoneFound: 'Aucune commande trouvée',
    orderCreateFirst: 'Créer la première commande',
    orderSeeDetails: 'Voir détails →',
    orderStatusAll: 'Toutes',
    orderSearchPlaceholder: 'Rechercher (référence, fournisseur, article, notes…)',
    orderCompany: 'Société',
    orderReference: 'Référence',
    orderSupplier: 'Fournisseur',
    orderDateLabel: 'Date de commande',
    orderExpectedDate: 'Date prévue de livraison',
    orderStatusLabel: 'Statut',
    orderNotesLabel: 'Notes',
    orderNoLines: 'Aucune ligne. Cliquez sur + Ajouter ligne',
    orderAddLine: '+ Ajouter ligne',
    orderAllSuperCats: 'Toutes super-catégories',
    orderAllCategories: 'Toutes catégories',
    orderSearchItem: 'Rechercher un article…',
    orderItemLabel: 'Article',
    orderQtyLabel: 'Qté',
    orderUnitPrice: 'Prix unit.',
    orderLineNote: 'Note de ligne',
    orderLineNotePlaceholder: 'Remarque spécifique à cet article…',
    orderNoItemFound: 'Aucun article trouvé',
    orderUpdateBtn: 'Mettre à jour',
    orderCreateBtn: 'Créer la commande',
    orderStatTotal: 'Total',
    orderStatPartielle: 'Partielles',
    orderStatRecues: 'Reçues',
    prTitle: 'Demandes de commande',
    prEnAttente: 'en attente',
    prSeeAll: 'Tout voir',
    prNonePending: 'Aucune demande en attente.',
    prNoneFound: 'Aucune demande trouvée.',
    prColImage: 'Image', prColItem: 'Article', prColQty: 'Qté demandée',
    prColNote: 'Note', prColBy: 'Demandé par', prColDate: 'Date',
    prColStatus: 'Statut', prColAction: 'Action',
    prStatusPending: 'En attente', prStatusDone: 'Commandé',
    prMarkOrdered: 'Marquer commandé', prTreated: 'Traité',
    prLoading: 'Chargement des demandes…',
    deleteOrderConfirm: 'Supprimer cette commande ?',
    orderItemDeleted: 'Article supprimé',
    orderAtLeastOneLine: 'Ajoutez au moins une ligne',
    orderPdfError: 'Erreur export PDF',
    // Projects / rest
    projectsTitle: 'Projets', addProject: 'Nouveau Projet', noProjects: 'Aucun projet trouvé',
    deleteProjectConfirm: 'Supprimer ce projet ? Le stock des barres sera restauré.',
    projectName: 'Nom du projet', reference: 'Référence', ralCode: 'Code RAL', ralColor: 'Couleur RAL', date: 'Date',
    backToProjects: 'Projets', tabChassis: 'Châssis', tabBars: 'Barres', tabVerre: 'Verre', tabAccessoires: 'Accessoires',
    addChassis: 'Ajouter châssis', exportPDF: 'Exporter PDF',
    chassis: 'Châssis', repere: 'Repère', type: 'Type', largeur: 'Largeur', hauteur: 'Hauteur',
    noChassis: 'Aucun châssis ajouté', deleteChassisConfirm: 'Supprimer ce châssis ?',
    etat_non_entame: 'Non entamé', etat_en_cours: 'En cours', etat_fabrique: 'Fabriqué', etat_livre: 'Livré',
    dormant: 'Dormant', vantail: 'Vantail',
    usedBarsTitle: 'Matériaux utilisés', noUsedBars: 'Aucun matériau ajouté',
    tabBL: 'Bons de livraison', noBL: 'Aucune livraison enregistrée',
    blTitle: 'Bon de Livraison', blDate: 'Date livraison', blPrint: 'Imprimer BL',
    mvEntrees: 'Entrées', mvSorties: 'Sorties', mvProjectUse: 'Sorties projet', mvProjectReturn: 'Retours projet',
    mv_entree: 'Entrée', mv_sortie: 'Sortie', mv_project_use: 'Sortie projet', mv_project_return: 'Retour projet',
    mv_order_reception: 'Réception commande',
    mvAll: 'Tous les types', mvRows: 'mouvements',
    mvColDate: 'Date', mvColType: 'Type', mvColItem: 'Article', mvColQty: 'Qté', mvColBalance: 'Solde', mvColProject: 'Projet', mvColNote: 'Note',
    kpiProjects: 'Projets', kpiInProgress: 'En cours', kpiItems: 'Articles stock',
    kpiCritical: 'Stock critique', kpiDeliveries: 'Livraisons ce mois', kpiMovements: 'Mouvements total',
    anStatusTitle: 'Répartition châssis par état', anCatTitle: 'Santé du stock par catégorie',
    anMonthlyTitle: 'Mouvements', periodDaily: 'Jour', periodMonthly: 'Mois', periodAnnual: 'Année',
    adminTitle: 'Administration', tabUsers: 'Utilisateurs', tabRoles: 'Rôles',
    newUser: 'Nouveau compte', newRole: 'Nouveau rôle',
    displayName: "Nom d'affichage", username: "Nom d'utilisateur",
    password: 'Mot de passe', role: 'Rôle', society: 'Société', active: 'Actif',
    receptionner: 'Réceptionner', articlesRecues: 'Articles reçus', articlesCommandes: 'Articles commandés',
    addNewOrder: 'Ajouter une commande', cons: 'Consommation',
    status_en_cours: 'En cours', status_fabrique: 'Fabriqué', status_cloture: 'Clôturé',
    selectAll: "Tout sélectionner", deselectAll: 'Tout desélectionner',
    searchInventory: "Chercher dans l'inventaire",
  },
  it: {
    appTitle: 'CAMI ALUMINIUM', appSubtitle: 'DA HB',
    etat_non_vitre: "Senza vetri",
    navInventory: 'Inventario', navOrders: 'Ordini', navProjects: 'Progetti',
    navClients: 'Clienti', navDevis: 'Preventivi', navMovements: 'Movimenti',
    navAnalytics: 'Dashboard', navAdmin: 'Admin',
    backCommandes: 'Torniamo agli ordini',
    Demandesadmin: "Richieste dell'amministratore",
    connectez: 'Accedi', utilisateur: 'Nome utente', mdp: 'Password',
    login_loading: 'Accesso in corso...', login_button: 'Accedere',
    mdpoubliécontactezadmin: "Password dimenticata? Contatta l'amministratore",
    allCompanies: 'Tutto', company: 'Società', language: 'Lingua',
    changePassword: 'Cambia password', logout: 'Disconnettersi',
    image: 'Immagine', designation: 'Designazione', quantity: 'Quantità',
    orderedQuantity: 'Qta Ordinata', threshold: 'Soglia', status: 'Stato',
    actions: 'Azioni', inStock: 'Disponibile', lowStock: 'Scorte Basse',
    criticalStock: 'Stock Critico', warningStock: 'Avviso Stock',
    edit: 'Modifica', delete: 'Elimina', add: 'Aggiungi',
    cancel: 'Annulla', save: 'Salva', confirm: 'Conferma',
    close: 'Chiudi', create: 'Crea', update: 'Aggiorna',
    loading: 'Caricamento...', noData: 'Nessun dato', refresh: 'Aggiorna',
    barStockRemaining: 'Stock rimanente',
    addNewItem: 'Aggiungi articolo', editItem: 'Modifica articolo',
    imageUrl: 'URL Immagine', quantityLabel: 'Quantità', orderedQuantityLabel: 'Qta Ordinata',
    thresholdLabel: 'Soglia Minima', categoryLabel: 'Categoria',
    noCategory: 'Nessuna Categoria', showAll: 'Mostra Tutto',
    searchPlaceholder: 'Cerca per designazione...',
    addCategory: 'Aggiungi Categoria', editCategory: 'Modifica Categoria',
    deleteConfirmMessage: 'Sei sicuro di voler eliminare questo articolo?',
    deleteCategoryConfirmMessage: 'Sei sicuro di voler eliminare questa categoria?',
    noItems: 'Nessun articolo trovato',
    exporting: 'Esportazione...', exportExcel: 'Esporta Excel',
    exportSuccess: 'Excel esportato', exportError: 'Errore esportazione',
    takeOutTitle: 'Preleva dal magazzino', takeOutAvailable: 'disponibile',
    takeOutQtyLabel: 'Quantità da prelevare', takeOutNoteLabel: 'Motivo / Nota',
    takeOutPlaceholder: 'es: Usato per...', takeOutConfirm: 'Conferma', takeOutCancel: 'Annulla',
    addInTitle: 'Aggiungere allo stock', addInQtyLabel: 'Quantità da aggiungere',
    addInPlaceholder: 'Motivo aggiunta...', addInConfirm: 'Conferma',
    errorUpdating: 'Errore di aggiornamento',
    addSuperCategory: 'Aggiungi super-categoria', superCategoryKey: 'Identificatore (unico)',
    superCategoryColor: 'Colore',
    deleteSuperCatConfirm: 'Eliminare questa super-categoria? Tutti gli articoli e categorie associati saranno interessati.',
    manageSuperCats: 'Gestisci super-categorie',
    poudre: 'Polvere', accessDenied: 'Accesso negato',
    searchInventory: "Cerca nell'inventario",
    // Orders
    orderDetailLinesTitle: 'Articoli ordinati',
    orderAlreadyReceived: 'Già ricevuto :',
    orderReceiveQtyLabel: 'Quantità totale ricevuta (cumulativa)',
    orderConfirmReceive: '✓ Conferma ricezione',
    orderReceiveTitle: 'Ricevere articoli',
    orderReceiveBtn: 'Ricevere',
    orderNotes: 'Note :',
    orderNew: 'Nuovo ordine',
    orderEdit: 'Modifica ordine',
    orderNoneFound: 'Nessun ordine trovato',
    orderCreateFirst: 'Crea il primo ordine',
    orderSeeDetails: 'Vedi dettagli →',
    orderStatusAll: 'Tutti',
    orderSearchPlaceholder: 'Cerca (riferimento, fornitore, articolo, note…)',
    orderCompany: 'Società',
    orderReference: 'Riferimento',
    orderSupplier: 'Fornitore',
    orderDateLabel: 'Data ordine',
    orderExpectedDate: 'Data prevista di consegna',
    orderStatusLabel: 'Stato',
    orderNotesLabel: 'Note',
    orderNoLines: 'Nessuna riga. Clicca + Aggiungi riga',
    orderAddLine: '+ Aggiungi riga',
    orderAllSuperCats: 'Tutte le super-categorie',
    orderAllCategories: 'Tutte le categorie',
    orderSearchItem: 'Cerca un articolo…',
    orderItemLabel: 'Articolo',
    orderQtyLabel: 'Qtà',
    orderUnitPrice: 'Prezzo unit.',
    orderLineNote: 'Nota riga',
    orderLineNotePlaceholder: 'Nota specifica per questo articolo…',
    orderNoItemFound: 'Nessun articolo trovato',
    orderUpdateBtn: 'Aggiorna',
    orderCreateBtn: 'Crea ordine',
    orderStatTotal: 'Totale',
    orderStatPartielle: 'Parziali',
    orderStatRecues: 'Ricevute',
    prTitle: 'Richieste di ordine',
    prEnAttente: 'in attesa',
    prSeeAll: 'Vedi tutto',
    prNonePending: 'Nessuna richiesta in attesa.',
    prNoneFound: 'Nessuna richiesta trovata.',
    prColImage: 'Immagine', prColItem: 'Articolo', prColQty: 'Qtà richiesta',
    prColNote: 'Nota', prColBy: 'Richiesto da', prColDate: 'Data',
    prColStatus: 'Stato', prColAction: 'Azione',
    prStatusPending: 'In attesa', prStatusDone: 'Ordinato',
    prMarkOrdered: 'Segna come ordinato', prTreated: 'Trattato',
    prLoading: 'Caricamento richieste…',
    deleteOrderConfirm: 'Eliminare questo ordine ?',
    orderItemDeleted: 'Articolo eliminato',
    orderAtLeastOneLine: 'Aggiungi almeno una riga',
    orderPdfError: 'Errore esportazione PDF',
    // Projects / rest
    projectsTitle: 'Progetti', addProject: 'Nuovo Progetto', noProjects: 'Nessun progetto trovato',
    deleteProjectConfirm: 'Eliminare questo progetto? Lo stock delle barre verrà ripristinato.',
    projectName: 'Nome progetto', reference: 'Riferimento', ralCode: 'Codice RAL', ralColor: 'Colore RAL', date: 'Data',
    backToProjects: 'Progetti', tabChassis: 'Telai', tabBars: 'Barre', tabVerre: 'Vetro', tabAccessoires: 'Accessori',
    addChassis: 'Aggiungi telaio', exportPDF: 'Esporta PDF',
    chassis: 'Telaio', repere: 'Repere', type: 'Tipo', largeur: 'Larghezza', hauteur: 'Altezza',
    noChassis: 'Nessun telaio aggiunto', deleteChassisConfirm: 'Eliminare questo telaio?',
    etat_non_entame: 'Non iniziato', etat_en_cours: 'In corso', etat_fabrique: 'Fabbricato', etat_livre: 'Consegnato',
    dormant: 'Dormiente', vantail: 'Anta',
    usedBarsTitle: 'Materiali utilizzati', noUsedBars: 'Nessun materiale aggiunto',
    tabBL: 'Bolle di consegna', noBL: 'Nessuna consegna registrata',
    blTitle: 'Bolla di Consegna', blDate: 'Data consegna', blPrint: 'Stampa BL',
    mvEntrees: 'Entrate', mvSorties: 'Uscite', mvProjectUse: 'Uscite progetto', mvProjectReturn: 'Resi progetto',
    mv_entree: 'Entrata', mv_sortie: 'Uscita', mv_project_use: 'Uscita progetto', mv_project_return: 'Reso progetto',
    mv_order_reception: 'Ricezione ordine',
    mvAll: 'Tutti i tipi', mvRows: 'movimenti',
    mvColDate: 'Data', mvColType: 'Tipo', mvColItem: 'Articolo', mvColQty: 'Qtà', mvColBalance: 'Saldo', mvColProject: 'Progetto', mvColNote: 'Nota',
    kpiProjects: 'Progetti', kpiInProgress: 'In corso', kpiItems: 'Articoli stock',
    kpiCritical: 'Stock critico', kpiDeliveries: 'Consegne questo mese', kpiMovements: 'Movimenti totali',
    anStatusTitle: 'Ripartizione telai per stato', anCatTitle: 'Salute stock per categoria',
    anMonthlyTitle: 'Movimenti', periodDaily: 'Giorno', periodMonthly: 'Mese', periodAnnual: 'Anno',
    adminTitle: 'Amministrazione', tabUsers: 'Utenti', tabRoles: 'Ruoli',
    newUser: 'Nuovo account', newRole: 'Nuovo ruolo',
    displayName: 'Nome visualizzato', username: 'Nome utente',
    password: 'Password', role: 'Ruolo', society: 'Società', active: 'Attivo',
    receptionner: 'Ricevere', articlesRecues: 'Articoli ricevuti', articlesCommandes: 'Articoli ordinati',
    addNewOrder: 'Aggiungere un ordine', cons: 'Consumo',
    status_en_cours: 'In corso', status_fabrique: 'Fabbricato', status_cloture: 'Chiuso',
  },
  en: {
    appTitle: 'CAMI ALUMINIUM', appSubtitle: 'BY HB',
    navInventory: 'Inventory', navOrders: 'Orders', navProjects: 'Projects',
    navClients: 'Clients', navDevis: 'Quotes', navMovements: 'Movements',
    navAnalytics: 'Dashboard', navAdmin: 'Admin',
    searchInventory: "Search in stock",
    backCommandes: 'Back to orders',
    Demandesadmin: 'Admin requests',
    connectez: 'Log in', utilisateur: 'Username', mdp: 'Password',
    login_loading: 'Logging in...', login_button: 'Sign in',
    mdpoubliécontactezadmin: 'Forgot password? Contact the administrator',
    barStockRemaining: 'Stock remaining',
    allCompanies: 'All', company: 'Company', language: 'Language',
    changePassword: 'Change password', logout: 'Sign out',
    image: 'Image', designation: 'Designation', quantity: 'Quantity',
    orderedQuantity: 'Ordered Qty', threshold: 'Threshold', status: 'Status',
    actions: 'Actions', inStock: 'In Stock', lowStock: 'Low Stock',
    criticalStock: 'Critical Stock', warningStock: 'Warning Stock',
    edit: 'Edit', delete: 'Delete', add: 'Add',
    cancel: 'Cancel', save: 'Save', confirm: 'Confirm',
    close: 'Close', create: 'Create', update: 'Update',
    loading: 'Loading...', noData: 'No data', refresh: 'Refresh',
    addNewItem: 'Add item', editItem: 'Edit item',
    imageUrl: 'Image URL', quantityLabel: 'Quantity', orderedQuantityLabel: 'Ordered Qty',
    thresholdLabel: 'Minimum Threshold', categoryLabel: 'Category',
    noCategory: 'No Category', showAll: 'Show All',
    searchPlaceholder: 'Search by designation...',
    addCategory: 'Add Category', editCategory: 'Edit Category',
    deleteConfirmMessage: 'Are you sure you want to delete this item?',
    deleteCategoryConfirmMessage: 'Are you sure you want to delete this category?',
    noItems: 'No items found',
    exporting: 'Exporting...', exportExcel: 'Export Excel',
    exportSuccess: 'Excel exported', exportError: 'Export error',
    takeOutTitle: 'Take out stock', takeOutAvailable: 'available',
    takeOutQtyLabel: 'Quantity to remove', takeOutNoteLabel: 'Reason / Note',
    takeOutPlaceholder: 'e.g. Used for...', takeOutConfirm: 'Confirm', takeOutCancel: 'Cancel',
    addInTitle: 'Add to stock', addInQtyLabel: 'Quantity to add',
    addInPlaceholder: 'Reason for addition...', addInConfirm: 'Confirm',
    errorUpdating: 'Error updating',
    addSuperCategory: 'Add super-category', superCategoryKey: 'Identifier (unique)',
    superCategoryColor: 'Color',
    deleteSuperCatConfirm: 'Delete this super-category? All associated items and categories will be affected.',
    manageSuperCats: 'Manage super-categories',
    poudre: 'Powder', accessDenied: 'Access denied',
    // Orders
    orderDetailLinesTitle: 'Ordered items',
    orderAlreadyReceived: 'Already received:',
    orderReceiveQtyLabel: 'Total quantity received (cumulative)',
    orderConfirmReceive: '✓ Confirm reception',
    orderReceiveTitle: 'Receive items',
    orderReceiveBtn: 'Receive',
    orderNotes: 'Notes:',
    orderNew: 'New order',
    orderEdit: 'Edit order',
    orderNoneFound: 'No orders found',
    orderCreateFirst: 'Create the first order',
    orderSeeDetails: 'See details →',
    orderStatusAll: 'All',
    orderSearchPlaceholder: 'Search (reference, supplier, item, notes…)',
    orderCompany: 'Company',
    orderReference: 'Reference',
    orderSupplier: 'Supplier',
    orderDateLabel: 'Order date',
    orderExpectedDate: 'Expected delivery date',
    orderStatusLabel: 'Status',
    orderNotesLabel: 'Notes',
    orderNoLines: 'No lines. Click + Add line',
    orderAddLine: '+ Add line',
    orderAllSuperCats: 'All super-categories',
    orderAllCategories: 'All categories',
    orderSearchItem: 'Search for an item…',
    orderItemLabel: 'Item',
    orderQtyLabel: 'Qty',
    orderUnitPrice: 'Unit price',
    orderLineNote: 'Line note',
    orderLineNotePlaceholder: 'Specific note for this item…',
    orderNoItemFound: 'No item found',
    orderUpdateBtn: 'Update',
    orderCreateBtn: 'Create order',
    orderStatTotal: 'Total',
    orderStatPartielle: 'Partial',
    orderStatRecues: 'Received',
    prTitle: 'Order requests',
    prEnAttente: 'pending',
    prSeeAll: 'See all',
    prNonePending: 'No pending requests.',
    prNoneFound: 'No requests found.',
    prColImage: 'Image', prColItem: 'Item', prColQty: 'Requested qty',
    prColNote: 'Note', prColBy: 'Requested by', prColDate: 'Date',
    prColStatus: 'Status', prColAction: 'Action',
    prStatusPending: 'Pending', prStatusDone: 'Ordered',
    prMarkOrdered: 'Mark as ordered', prTreated: 'Processed',
    prLoading: 'Loading requests…',
    deleteOrderConfirm: 'Delete this order?',
    orderItemDeleted: 'Item deleted',
    orderAtLeastOneLine: 'Add at least one line',
    orderPdfError: 'PDF export error',
    // Projects / rest
    projectsTitle: 'Projects', addProject: 'New Project', noProjects: 'No projects found',
    deleteProjectConfirm: 'Delete this project? Bar stock will be restored.',
    projectName: 'Project name', reference: 'Reference', ralCode: 'RAL Code', ralColor: 'RAL Color', date: 'Date',
    backToProjects: 'Projects', tabChassis: 'Chassis', tabBars: 'Bars', tabVerre: 'Glass', tabAccessoires: 'Accessories',
    addChassis: 'Add Chassis', exportPDF: 'Export PDF',
    chassis: 'Chassis', repere: 'ID', type: 'Type', largeur: 'Width', hauteur: 'Height',
    noChassis: 'No chassis added yet', deleteChassisConfirm: 'Delete this chassis?',
    etat_non_entame: 'Not Started', etat_en_cours: 'In Progress', etat_fabrique: 'Fabricated', etat_livre: 'Delivered',
    dormant: 'Frame', vantail: 'Leaf',
    usedBarsTitle: 'Materials used', noUsedBars: 'No materials added yet',
    tabBL: 'Delivery Notes', noBL: 'No deliveries recorded',
    blTitle: 'Delivery Note', blDate: 'Delivery date', blPrint: 'Print DN',
    mvEntrees: 'Receipts', mvSorties: 'Issues', mvProjectUse: 'Project use', mvProjectReturn: 'Project returns',
    mv_entree: 'Receipt', mv_sortie: 'Issue', mv_project_use: 'Project use', mv_project_return: 'Project return',
    mv_order_reception: 'Order reception',
    mvAll: 'All types', mvRows: 'movements',
    mvColDate: 'Date', mvColType: 'Type', mvColItem: 'Item', mvColQty: 'Qty', mvColBalance: 'Balance', mvColProject: 'Project', mvColNote: 'Note',
    kpiProjects: 'Projects', kpiInProgress: 'In progress', kpiItems: 'Stock items',
    kpiCritical: 'Critical stock', kpiDeliveries: 'Deliveries this month', kpiMovements: 'Total movements',
    anStatusTitle: 'Chassis status breakdown', anCatTitle: 'Stock health by category',
    anMonthlyTitle: 'Movements', periodDaily: 'Daily', periodMonthly: 'Monthly', periodAnnual: 'Annual',
    adminTitle: 'Administration', tabUsers: 'Users', tabRoles: 'Roles',
    newUser: 'New account', newRole: 'New role',
    displayName: 'Display name', username: 'Username',
    password: 'Password', role: 'Role', society: 'Company', active: 'Active',
    receptionner: 'Receive', articlesRecues: 'Received items', articlesCommandes: 'Ordered items',
    addNewOrder: 'Add an order', cons: 'Consumption',
    status_en_cours: 'In Progress', status_fabrique: 'Fabricated', status_cloture: 'Closed',
    etat_non_vitre: "Without glazing",
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(LANGUAGES.FR);
  const changeLanguage = useCallback((lang) => {
    if (Object.values(LANGUAGES).includes(lang)) setCurrentLanguage(lang);
  }, []);
  const t = useCallback((key) => translations[currentLanguage]?.[key] || translations.fr?.[key] || key, [currentLanguage]);
  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t, languages: LANGUAGES, languageLabels: LANGUAGE_LABELS }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export default LanguageContext;